---
name: Automated review
on:  # yamllint disable-line rule:truthy
  pull_request:
    types:
    - opened
    - reopened
    - review_requested

permissions:
  pull-requests: write

jobs:
  automated_review:
    name: Generate automated review
    runs-on: ubuntu-latest
    if: ${{ github.event.action != 'review_requested' || github.event.requested_reviewer.login == 'github-actions[bot]' }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ros-infrastructure/rosdistro-reviewer@main
      with:
        token: ${{ github.token }}
