---
name: Automated review
on:
  pull_request:
    types:
      - opened
      - reopened
      - review_requested

permissions:
  pull-requests: write

jobs:
  automated_review:
    name: Generate automated review
    runs-on: ubuntu-latest
    #if: ${{ !(github.event.requested_reviewer) || github.event.requested_reviewer.login == 'github-actions' }}
    steps:
    - run: echo '${{ toJSON(github) }}' >> $GITHUB_STEP_SUMMARY
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: python3 -m pip install ./rosdistro_utils
    - run: python3 -m rosdistro_utils ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.number }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
